### ISSUE TITLE
Error maxBuffer

### ISSUE THREAD

**Issue by camxuyen** [node-js-libs/packnode#4]
Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:792:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

Please help me fix it

**Comment by chriso** [comment]
Can you provide an example of the code that leads to the error? That stack trace is not helpful at all, and may not even originate in the library.
